 USE LEARNING;
 CREATE TABLE EMPLOYEE
 (
 ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 EMPNAME VARCHAR(30) NOT NULL,
 EMPROLE VARCHAR(20) NOT NULL,
 DOJ DATE NOT NULL,
 PRIMARY KEY(ID)
);

INSERT INTO EMPLOYEE (EMPNAME,EMPROLE,DOJ)
VALUES
('RAMU','HR','2023-08-10'),
('SEETHA','MARKETING','2023-08-12'),
('VINAY','SUPPORT','2023-08-14'),
('KAVIYA','JAVA_DEVELOPER','2023-08-21'),
('HARITHA','QA','2023-09-10');
SHOW TABLES;
SELECT * FROM EMPLOYEE;
CREATE TABLE SALARY 
(
SID INT NOT NULL AUTO_INCREMENT,
SALID INT NOT NULL,
SALDATE DATE NOT NULL,
AMOUNT INT NOT NULL,
PRIMARY KEY(SID)
);

INSERT INTO SALARY (SALID,SALDATE,AMOUNT)
VALUES
(1,'2023-09-01',50000),
(2,'2023-09-01',47000),
(3,'2023-09-01',47000),
(4,'2023-09-01',45000);

SELECT * FROM SALARY;
SELECT * FROM EMPLOYEE;

-- JOIN QUEERIES
-- BOTH TABLE HAVING SAME MATCH USE 'INNER JOIN'
 SELECT EMPLOYEE.EMPNAME,SALARY.AMOUNT
 FROM EMPLOYEE
 INNER JOIN SALARY
 ON EMPLOYEE.ID=SALARY.SID;
 
 
 -- BOTH TABLE LEFT JOIN 
 SELECT EMPLOYEE.EMPNAME,EMPLOYEE.EMPROLE,SALARY.AMOUNT
 FROM EMPLOYEE LEFT JOIN SALARY
 ON EMPLOYEE.ID =SALARY.SID;

 -- BOTH TABLE RIGHT JOIN 
 SELECT EMPLOYEE.EMPNAME,EMPLOYEE.EMPROLE,SALARY.AMOUNT
 FROM EMPLOYEE RIGHT JOIN SALARY
 ON EMPLOYEE.ID =SALARY.SID;

SELECT * FROM ATTENDANCE;
SELECT * FROM STUDENTS;

-- USING JOIN QUERY WE CAN MERGE THE TWO TABLES  AND DISPLAY IT
SELECT STUDENTS.STUDNAME,STUDENTS.CITY,
ATTENDANCE.SDATE, ATTENDANCE.SSTATUS
FROM STUDENTS INNER JOIN ATTENDANCE
ON  STUDENTS.ID=ATTENDANCE.SID;


-- PROVIDING SCHOLARSHIP AMOUNT FOR STUDENTS ACCORDING TO CITY
SELECT STUDNAME,CITY,
(
CASE
WHEN CITY='SALEM' THEN 4000
WHEN CITY='HOSUR' THEN 3000
WHEN CITY='CHENNAI' THEN 2000
WHEN CITY='MUMBAI' THEN 1000
ELSE 0
END
) AS STIPHENED FROM STUDENTS;



-- PROVIDING SCHOLARSHIP AMOUNT FOR STUDENTS FOR SALEM 
SELECT STUDNAME, CITY,
(
CASE
WHEN CITY='SALEM' THEN 4000
WHEN CITY='HOSUR' THEN 3000
WHEN CITY='CHENNAI' THEN 2000
WHEN CITY='MUMBAI' THEN 1000
ELSE 0
END
) AS STIPHENED FROM STUDENTS WHERE CITY='SALEM';


