USE LEARNING;
CREATE TABLE PRODUCT
(
PID INT NOT NULL AUTO_INCREMENT,
PRODUCTNAME VARCHAR(25) NOT NULL,
RATE INT NOT NULL,
PRIMARY KEY(PID)
);

INSERT INTO PRODUCT (PRODUCTNAME,RATE)
VALUES 
('POETRY',1000),
('HORROR',200),
('STORY',500),
('CRIME',700),
('NOVEL',600);

SELECT * FROM PRODUCT;

-- ---------------------------------------------------------------------
CREATE TABLE PRICE_LOGS 
(
ID INT NOT NULL AUTO_INCREMENT,
PRODUCTID INT NOT NULL,
OLD_PRICE INT NOT NULL,
NEW_PRICE INT NOT NULL,
PRIMARY KEY(ID)
);
-- ------------------------------------------------------
DELIMITER $$
-- TRIGGER
CREATE TRIGGER BEF_PROD_UPDATES
BEFORE UPDATE ON PRODUCT
FOR EACH ROW
BEGIN
INSERT INTO PRICE_LOGS(PRODUCTID,OLD_PRICE,NEW_PRICE)
VALUES (OLD.PID,OLD.RATE,NEW.RATE);
END$$

-- -----------------------------------------------
SELECT * FROM PRICE_LOGS;
UPDATE PRODUCT SET RATE=3000 WHERE PRODUCTNAME='POETRY';
SELECT * FROM PRICE_LOGS;